#!/usr/bin/env python
import sys
import BaseHTTPServer
import re
import mimetypes
import sqlite3
import os.path
import os
import csv

PORT_NUMBER=8000

transactions = re.compile('^data.csv$')

class Handler(BaseHTTPServer.BaseHTTPRequestHandler):
  def do_GET(s):
    p = s.path[1:] #remove slash from front of url
    try:
      f = open(p)
      
      s.send_response(200)
      s.send_header("Content-type", mimetypes.MimeTypes().guess_type(p)[0])
      s.end_headers()
      
      s.wfile.write(f.read())
      f.close()
      
    except IOError:
    
      if transactions.match(p):
        
        items = os.listdir('data')
        
        s.wfile.write('name,\n')
        
        for i in items:
        
          s.wfile.write('data' + os.path.sep + i)
          s.wfile.write(',')
          s.wfile.write('\n')
            
        
      else:
        s.send_error(404, 'File not found')

if __name__ == '__main__':
  srv = BaseHTTPServer.HTTPServer
  httpd = srv(('', PORT_NUMBER), Handler)
  print "Server started"
  try:
    httpd.serve_forever()
  except KeyboardInterrupt:
    pass
  httpd.server_close()
  print "Server stopped"
