#!/bin/sh

DIR=downloads
LOG=downloads.log

i=1
while [ 1 ]
do
  if [[ -f $LOG ]]
  then
    LOG=downloads${i}.log
    ((i++))
    continue
  fi
  break
done

found=1

for cfg in *.repo
do
  for r in `cat $cfg | egrep '^\[.*\]$' | sed 's/^\[\(.*\)\]$/\1/g' | sort | uniq`
  do
    echo "Checking repo $r" >> $LOG
    yumdownloader --destdir=$DIR --disablerepo=* --config=$cfg --enablerepo=$r $* 2>&1 | tee -a $LOG > /dev/null
    if [ ${PIPESTATUS[0]} -eq 0 ]
    then
      echo "Packages found on repo $r" | tee -a $LOG
      found=0
    fi
  done
done

exit $found
