#!/usr/bin/env python
import sys
import BaseHTTPServer
import re
import mimetypes
import sqlite3
import os.path
import csv

PORT_NUMBER=8000

transactions = re.compile('^transactions.csv$')

class Handler(BaseHTTPServer.BaseHTTPRequestHandler):
  def do_GET(s):
    p = s.path[1:] #remove slash from front of url
    try:
      f = open(p)
      
      s.send_response(200)
      s.send_header("Content-type", mimetypes.MimeTypes().guess_type(p)[0])
      s.end_headers()
      
      s.wfile.write(f.read())
      f.close()
      
    except IOError:
    
      if transactions.match(p) and os.path.isfile('transactions.dat'):
        try:
          conn = sqlite3.connect('transactions.dat')
          conn.row_factory = sqlite3.Row
          curr = conn.cursor()
          
          curr.execute('PRAGMA table_info(\'transactions\')')
          pragma = []
          
          for row in curr:
            pragma.append(row[1])
          
          out = csv.writer(s.wfile)
          out.writerow(pragma)
          
          curr.execute('SELECT * FROM transactions')
          data = curr.fetchall()
          out.writerows(data)
            
          conn.close()
        except sqlite3.Error:
          s.send_error(503, 'Could not open database')
        
      else:
        s.send_error(404, 'File not found')

if __name__ == '__main__':
  srv = BaseHTTPServer.HTTPServer
  httpd = srv(('', PORT_NUMBER), Handler)
  print "Server started"
  try:
    httpd.serve_forever()
  except KeyboardInterrupt:
    pass
  httpd.server_close()
  print "Server stopped"
