#!/usr/bin/env python
import BaseHTTPServer
import mimetypes

PORT_NUMBER=8000

class Handler(BaseHTTPServer.BaseHTTPRequestHandler):
  def do_GET(s):
    p = s.path[1:] #remove slash from front of url
    try:
      f = open(p)
      
      s.send_response(200)
      s.send_header("Content-type", mimetypes.MimeTypes().guess_type(p)[0])
      s.end_headers()
      
      s.wfile.write(f.read())
      f.close()
      
    except IOError:
      s.send_error(404, 'File not found')
  

if __name__ == '__main__':
  srv = BaseHTTPServer.HTTPServer
  httpd = srv(('', PORT_NUMBER), Handler)
  print "Server started"
  try:
    httpd.serve_forever()
  except KeyboardInterrupt:
    pass
  httpd.server_close()
  print "Server stopped"
