#!/usr/bin/env python
import os
import subprocess
from bottle import route, run, template, static_file, response

@route('/bower_components/<path:path>')
def bower_components(path):
  return static_file(path, root='./bower_components')

@route('/icons/<path:path>')
def icons(path):
  return static_file(path, root='./icons')
  
@route('/exif/<path:path>')
def icons_exifinfo(path):
  
  exiffile = ".exif.{}.json".format(os.path.basename(path))
  exifpath1 = os.path.join(os.path.dirname(path), exiffile)
  exifpath2 = os.path.realpath(os.path.join('./icons',exifpath1))
  
  if os.path.isfile(exifpath2):
    print "EXIF CACHE",exifpath2
    return static_file(exifpath1, root='./icons')
  
  print "NO EXIF",path,exifpath2
  
  exifinfo = subprocess.Popen("exiftool -j '{}'".format(os.path.realpath(os.path.join('./icons',path))), shell=True, stdout=subprocess.PIPE).stdout.read()
  
  fd = open(exifpath2, "w")
  fd.write(exifinfo)
  fd.close()
  
  return static_file(exifpath1, root='./icons')

@route('/index.html')
def index():
  return static_file('index.html', root='.')

@route('/index.js')
def index3_js():
  return static_file('index.js', root='.')
  
run(host='localhost', port=8000)
