#!/usr/bin/env python
import os
import subprocess
from bottle import route, run, template, static_file, response

@route('/bower_components/<path:path>')
def bower_components(path):
  return static_file(path, root='./bower_components')

@route('/icons/<path:path>')
def icons(path):
  return static_file(path, root='./icons')
  
@route('/exif/<path:path>')
def icons_exifinfo(path):
  return subprocess.Popen("exiftool -j '{}'".format(os.path.realpath(os.path.join('./icons',path))), shell=True, stdout=subprocess.PIPE).stdout.read()

@route('/index.html')
def index():
  return static_file('index.html', root='.')

@route('/index.js')
def index3_js():
  return static_file('index.js', root='.')
  
run(host='localhost', port=8000)
