#!/usr/bin/env python

from bottle import route, run, template, static_file

@route('/hello/<name>')
def index(name):
    return template('<b>Hello {{name}}</b>!', name=name)

@route('/bower_components/<path:path>')
def bower_components(path):
  return static_file(path, root='./bower_components')

@route('/index.html')
def index():
  return static_file('index.html', root='.')

@route('/tcx_parser.js')
def tcx_parser():
  return static_file('tcx_parser.js', root='.')

@route('/tcx_to_csv.xsl')
def tcx_to_csv():
  return static_file('tcx_to_csv.xsl', root='.')

@route('/tcx.xml')
def tcx():
  return static_file('tcx.xml', root='.')

run(host='localhost', port=8000)


