#!/usr/bin/env python

import lxml.etree as ET
from bottle import route, run, template, static_file, response

xslt = ET.parse('tcx_to_csv.xsl')
transform = ET.XSLT(xslt)

@route('/hello/<name>')
def index(name):
    return template('<b>Hello {{name}}</b>!', name=name)

@route('/bower_components/<path:path>')
def bower_components(path):
  return static_file(path, root='./bower_components')

@route('/activities/<path:path>')
def activities_tcx(path):
  dom = ET.parse('./activities/%s' %(path))
  response.content_type = 'text/text'
  return str(transform(dom))

@route('/index.html')
def index():
  return static_file('index.html', root='.')

@route('/index2.html')
def index2():
  return static_file('index2.html', root='.')

@route('/index3.html')
def index3():
  return static_file('index3.html', root='.')

@route('/index3.js')
def index3_js():
  return static_file('index3.js', root='.')

@route('/tcx_parser.js')
def tcx_parser():
  return static_file('tcx_parser.js', root='.')

@route('/utils.js')
def tcx_parser():
  return static_file('utils.js', root='.')
  
@route('/tcx_to_csv.xsl')
def tcx_to_csv():
  return static_file('tcx_to_csv.xsl', root='.')

@route('/tcx.xml')
def tcx():
  return static_file('tcx.xml', root='.')
  
@route('/activities.csv')
def activities():
  return static_file('activities/Activities.txt', root='.')

run(host='localhost', port=8000)


